const locations = [
  {
    lat: 37.2576,
    lng: 13.9181,
    name: "Campobello di Licata",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5129,
    lng: 14.9698,
    name: "Motta Sant'Anastasia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6521,
    lng: 15.0947,
    name: "Fleri",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.8805,
    lng: 15.3074,
    name: "Letojanni",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 52.2693,
    lng: 4.5483,
    name: "Keukenhof",
    nation: "Netherlands",
    continent: "Europe",
  },
  {
    lat: 52.3702,
    lng: 4.8951,
    name: "Amsterdam",
    nation: "Netherlands",
    continent: "Europe",
  },
  {
    lat: 37.4306,
    lng: 14.4786,
    name: "Morgantina",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.014118,
    lng: 14.324206,
    name: "Blue Lagoon",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 36.0436,
    lng: 14.243,
    name: "Rabat, Gozo",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 36.0264,
    lng: 14.285,
    name: "Ghajnsielem, Gozo",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.9125,
    lng: 14.5019,
    name: "Sliema",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.9181,
    lng: 14.4883,
    name: "St Julian",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.9608,
    lng: 14.3413,
    name: "Popeye Village",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 40.7128,
    lng: -74.006,
    name: "New York",
    nation: "United States",
    continent: "North America",
  },
  {
    lat: 35.9878,
    lng: 14.3533,
    name: "Marfa",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.936,
    lng: 14.3966,
    name: "St Paul's Bay",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.9523,
    lng: 14.35,
    name: "Mellieħa",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.8997,
    lng: 14.5147,
    name: "La Valletta",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.8658,
    lng: 14.5119,
    name: "Tarxien",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.8561,
    lng: 14.5043,
    name: "Santa Lucia",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.8411,
    lng: 14.5393,
    name: "Marsaxlokk",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.9097,
    lng: 14.4261,
    name: "Mosta",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 35.8858,
    lng: 14.403,
    name: "Mdina",
    nation: "Malta",
    continent: "Europe",
  },
  {
    lat: 37.7866,
    lng: 15.2362,
    name: "Marina di Cottone",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.2733,
    lng: 14.79,
    name: "Militello in Val di Catania",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.3289,
    lng: 14.4436,
    name: "Mirabella Imbaccari",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.7901,
    lng: 14.7028,
    name: "Scicli",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7086,
    lng: 15.2175,
    name: "Torre Archirafi",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.099,
    lng: 9.7375,
    name: "Riomaggiore",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.106,
    lng: 9.729,
    name: "Manarola",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.1197,
    lng: 9.7086,
    name: "Corniglia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.133,
    lng: 9.683,
    name: "Vernazza",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.1458,
    lng: 9.6542,
    name: "Monterosso al Mare",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.8175,
    lng: 7.775,
    name: "Sanremo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.4111,
    lng: 8.9328,
    name: "Genova",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.2939,
    lng: 14.8428,
    name: "Scordia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.2649,
    lng: 14.6938,
    name: "Mineo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.3282,
    lng: 14.7467,
    name: "Palagonia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.408,
    lng: 11.8859,
    name: "Padova",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.7303,
    lng: 14.8467,
    name: "Pozzallo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.7853,
    lng: 14.9069,
    name: "Ispica",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.7429,
    lng: 15.117,
    name: "Marzamemi",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.7165,
    lng: 14.7846,
    name: "Marina di Modica",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.1083,
    lng: 13.9469,
    name: "Licata",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.7847,
    lng: 14.5503,
    name: "Marina di Ragusa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 41.3902,
    lng: 2.154,
    name: "Barcellona",
    nation: "Spain",
    continent: "Europe",
  },
  {
    lat: 48.8014,
    lng: 2.1301,
    name: "Versailles",
    nation: "France",
    continent: "Europe",
  },
  {
    lat: 48.8647,
    lng: 2.349,
    name: "Parigi",
    nation: "France",
    continent: "Europe",
  },
  {
    lat: 51.1788,
    lng: -1.8263,
    name: "Stonehenge",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 50.8284,
    lng: -0.1395,
    name: "Brighton",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 48.8674,
    lng: 2.784,
    name: "Disneyland Paris",
    nation: "France",
    continent: "Europe",
  },
  {
    lat: 51.38,
    lng: -2.36,
    name: "Bath",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 51.752,
    lng: -1.2577,
    name: "Oxford",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 51.4817,
    lng: -0.6136,
    name: "Windsor",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 52.1917,
    lng: -1.7073,
    name: "Stratford-upon-Avon",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 40.5754,
    lng: 15.7817,
    name: "Pignola",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.4752,
    lng: 14.6532,
    name: "Giumarra",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5297,
    lng: 14.5756,
    name: "Libertinia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7475,
    lng: 14.3922,
    name: "Nicosia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.3167,
    lng: 13.5833,
    name: "Agrigento",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.2161,
    lng: 14.5176,
    name: "Caltagirone",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.1167,
    lng: 13.3667,
    name: "Palermo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.3842,
    lng: 14.3692,
    name: "Piazza Armerina",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.1912,
    lng: 13.2469,
    name: "Isola delle Femmine",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5231,
    lng: 15.0081,
    name: "Misterbianco",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.4951,
    lng: 14.6537,
    name: "Castel di Iudica",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.3852,
    lng: 14.6937,
    name: "Ramacca",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.2144,
    lng: 14.6368,
    name: "Grammichele",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.965,
    lng: 15.2149,
    name: "Fontane Bianche",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.075,
    lng: 15.281,
    name: "Siracusa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.617,
    lng: 14.9,
    name: "Santa Maria di Licodia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.4922,
    lng: 15.0704,
    name: "Catania",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6174,
    lng: 15.0242,
    name: "Nicolosi",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.532,
    lng: 15.093,
    name: "Canalicchio",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.568,
    lng: 15.158,
    name: "Aci Trezza",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5556,
    lng: 15.1458,
    name: "Aci Castello",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.193,
    lng: 15.553,
    name: "Messina",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.763,
    lng: 15.214,
    name: "Fondachello",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7244,
    lng: 15.1817,
    name: "Giarre",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6205,
    lng: 15.1734,
    name: "Santa Maria La Scala",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.618,
    lng: 15.057,
    name: "Pedara",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6918,
    lng: 15.1041,
    name: "Zafferana Etnea",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5759,
    lng: 15.0732,
    name: "Tremestieri Etneo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6521,
    lng: 15.1941,
    name: "Stazzo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5782,
    lng: 15.095,
    name: "San Giovanni la Punta",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.614,
    lng: 15.166,
    name: "Acireale",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.65,
    lng: 14.867,
    name: "Biancavilla",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6857,
    lng: 15.1344,
    name: "Santa Venerina",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6358,
    lng: 15.1758,
    name: "Santa Tecla",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.5736,
    lng: 15.0437,
    name: "Mascalucia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.698,
    lng: 15.1726,
    name: "Trepunti",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.617,
    lng: 15.083,
    name: "Trecastagni",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7181,
    lng: 15.1656,
    name: "Macchia di Giarre",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.933,
    lng: 14.1,
    name: "Castelbuono",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.737,
    lng: 15.204,
    name: "Riposto",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7227,
    lng: 15.1146,
    name: "Milo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7427,
    lng: 15.1392,
    name: "Sant'Alfio",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.8997,
    lng: 15.1478,
    name: "Francavilla di Sicilia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.8385,
    lng: 15.142,
    name: "Linguaglossa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.1737,
    lng: 14.8993,
    name: "Gioiosa Marea",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.0386,
    lng: 14.0229,
    name: "Cefalù",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.8885,
    lng: 15.113,
    name: "Castiglione di Sicilia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7578,
    lng: 15.1977,
    name: "Mascali",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.922,
    lng: 15.347,
    name: "Sant'Alessio Siculo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.9547,
    lng: 15.367,
    name: "Santa Teresa di Riva",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.8278,
    lng: 15.2652,
    name: "Giardini Naxos",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.8536,
    lng: 15.2885,
    name: "Taormina",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 40.73,
    lng: 13.9,
    name: "Ischia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 40.8518,
    lng: 14.2681,
    name: "Napoli",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 40.7415,
    lng: 14.485,
    name: "Pompei",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.39,
    lng: 11.2232,
    name: "Monteriggioni",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.0694,
    lng: 12.619,
    name: "Assisi",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 41.0711,
    lng: 14.333,
    name: "Caserta",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 41.8919,
    lng: 12.5113,
    name: "Roma",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.4738,
    lng: 11.0298,
    name: "San Gimignano",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.4938,
    lng: 11.3388,
    name: "Bologna",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.7085,
    lng: 10.4036,
    name: "Pisa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.7696,
    lng: 11.2558,
    name: "Firenze",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.4371,
    lng: 12.3346,
    name: "Venezia",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 43.3188,
    lng: 11.3307,
    name: "Siena",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 44.0592,
    lng: 12.5683,
    name: "Rimini",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.4858,
    lng: 12.4172,
    name: "Burano",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.4586,
    lng: 12.3568,
    name: "Murano",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.1333,
    lng: 10.025,
    name: "Cremona",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.4384,
    lng: 10.9916,
    name: "Verona",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.0703,
    lng: 7.6869,
    name: "Torino",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.4642,
    lng: 9.19,
    name: "Milano",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.5487,
    lng: 9.0409,
    name: "Rho",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 45.4483,
    lng: 8.6233,
    name: "Novara",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.9257,
    lng: 14.7244,
    name: "Ragusa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.0176,
    lng: 12.5362,
    name: "Trapani",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.8924,
    lng: 15.0652,
    name: "Noto",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 36.85,
    lng: 14.7667,
    name: "Modica",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.571,
    lng: 14.6919,
    name: "Catenanuova",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.6507,
    lng: 15.1807,
    name: "Scillichenti",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 46.4307,
    lng: 11.6857,
    name: "Pozza di Fassa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 46.4767,
    lng: 11.7703,
    name: "Canazei",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 46.3764,
    lng: 11.6616,
    name: "Moena",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 46.4189,
    lng: 11.6742,
    name: "Vigo di Fassa",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.7888,
    lng: 14.836,
    name: "Bronte",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.0815,
    lng: 13.289,
    name: "Monreale",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.0738,
    lng: 13.1083,
    name: "Borgo Parrini",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 38.1515,
    lng: 13.0827,
    name: "Terrasini",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.9779,
    lng: 12.9647,
    name: "Alcamo",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.798,
    lng: 12.437,
    name: "Marsala",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.2901,
    lng: 13.4736,
    name: "Scala dei Turchi",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.1269,
    lng: 14.8481,
    name: "Buccheri",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 37.1613,
    lng: 14.7489,
    name: "Vizzini",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 51.5085,
    lng: -0.1257,
    name: "Londra",
    nation: "United Kingdom",
    continent: "Europe",
  },
  {
    lat: 37.1485,
    lng: 14.3878,
    name: "Niscemi",
    nation: "Italy",
    continent: "Europe",
  },
  {
    lat: 40.6401,
    lng: 22.9444,
    name: "Salonicco",
    nation: "Greece",
    continent: "Europe",
  },
];
